// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Ai_Reports_Context))]
    [Migration("20251223151542_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.TbAuthority", b =>
                {
                    b.Property<int>("Authority_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Authority_ID"));

                    b.Property<string>("Authority_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Authority_ID");

                    b.HasIndex("Authority_Name", "Department_Name")
                        .IsUnique();

                    b.ToTable("TbAuthority", (string)null);
                });

            modelBuilder.Entity("Database.TbAuthority_Contact", b =>
                {
                    b.Property<int>("Contact_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contact_Id"));

                    b.Property<int>("Authority_ID")
                        .HasColumnType("int");

                    b.Property<string>("Contact_Info")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Contact_Id");

                    b.HasIndex("Authority_ID", "Contact_Info")
                        .IsUnique();

                    b.ToTable("TbAuthority_Contact", (string)null);
                });

            modelBuilder.Entity("Database.TbCitizen", b =>
                {
                    b.Property<int>("Citizen_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Citizen_ID"));

                    b.Property<string>("Citizen_Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Citizen_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Citizen_National_Id")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .IsFixedLength();

                    b.HasKey("Citizen_ID");

                    b.HasIndex("Citizen_Email")
                        .IsUnique();

                    b.HasIndex("Citizen_National_Id")
                        .IsUnique();

                    b.ToTable("TbCitizen", (string)null);
                });

            modelBuilder.Entity("Database.TbCitizen_Phone", b =>
                {
                    b.Property<int>("Phone_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Phone_Id"));

                    b.Property<int>("Citizen_ID")
                        .HasColumnType("int");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.HasKey("Phone_Id");

                    b.HasIndex("Citizen_ID");

                    b.HasIndex("Phone_Number")
                        .IsUnique();

                    b.ToTable("TbCitizen_Phone", (string)null);
                });

            modelBuilder.Entity("Database.TbHandle", b =>
                {
                    b.Property<int>("Report_ID")
                        .HasColumnType("int");

                    b.Property<int>("Authority_ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update_Report")
                        .HasColumnType("datetime2");

                    b.HasKey("Report_ID", "Authority_ID");

                    b.HasIndex("Authority_ID");

                    b.ToTable("TbHandle", (string)null);
                });

            modelBuilder.Entity("Database.TbReport", b =>
                {
                    b.Property<int>("Report_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Report_ID"));

                    b.Property<DateTime>("AiTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Citizen_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence_Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Report_Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report_Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Report_GeoLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Report_PredictedCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Report_Submit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("In Progress");

                    b.HasKey("Report_ID");

                    b.HasIndex("Citizen_ID");

                    b.ToTable("TbReport", (string)null);
                });

            modelBuilder.Entity("Database.TbAuthority_Contact", b =>
                {
                    b.HasOne("Database.TbAuthority", "Authority")
                        .WithMany("LstAuthorityContacts")
                        .HasForeignKey("Authority_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");
                });

            modelBuilder.Entity("Database.TbCitizen_Phone", b =>
                {
                    b.HasOne("Database.TbCitizen", "Citizen")
                        .WithMany("LstPhone")
                        .HasForeignKey("Citizen_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("Database.TbHandle", b =>
                {
                    b.HasOne("Database.TbAuthority", "Authority")
                        .WithMany("LstHandle")
                        .HasForeignKey("Authority_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.TbReport", "Report")
                        .WithMany("LstHandle")
                        .HasForeignKey("Report_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Database.TbReport", b =>
                {
                    b.HasOne("Database.TbCitizen", "Citizen")
                        .WithMany("LstReport")
                        .HasForeignKey("Citizen_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("Database.TbAuthority", b =>
                {
                    b.Navigation("LstAuthorityContacts");

                    b.Navigation("LstHandle");
                });

            modelBuilder.Entity("Database.TbCitizen", b =>
                {
                    b.Navigation("LstPhone");

                    b.Navigation("LstReport");
                });

            modelBuilder.Entity("Database.TbReport", b =>
                {
                    b.Navigation("LstHandle");
                });
#pragma warning restore 612, 618
        }
    }
}
